### ISSUE TITLE
Review styleguide writing

### ISSUE THREAD

**Issue by jaime-lynn** [ritterim/pui-website#131]
In order to prepare Platform UI for public release, we would like to review the writing in all sections of the styleguide to make sure that it is consistent, concise, and makes sense. The style should be friendly and colloquial.

Sections are as follows:
- [ ] Main Page
- Getting Started
  - [ ] Get Started
  - [ ] Accessibility
  - [ ] Installation
- Components
  - [ ] Accordion
  - [ ] Blockquote
  - [ ] Buttons
  - [ ] Cards
  - [ ] Drawer
  - [ ] Figure Hover
  - [ ] Image Round
  - [ ] Info Box
  - [ ] Lists
  - [ ] Messages
  - [ ] Modal
  - [ ] Pill
  - [ ] Tabs
  - [ ] Tooltip
- Errors
  - [ ] Errors
- Forms
  - [ ] Forms
- Icons
  - [ ] Icons
- Layout
  - [ ] Blocks
  - [ ] Flex
- Menus
  - [ ] Menu
- Tables
  - [ ] Tables
- Typography
  - [ ] Typography
- Utilities
  - [ ] Backgrounds
  - [ ] Borders
  - [ ] Cursor Pointer
  - [ ] Display
  - [ ] Height and Width
  - [ ] Loader
  - [ ] Overflow
  - [ ] Position
  - [ ] Rotate
  - [ ] Scale Hover
  - [ ] Screen Reader Only
  - [ ] Shadow Hover
  - [ ] Spacers
  - [ ] SVG Height
  - [ ] Transition
  - [ ] Truncate With Ellipsis

**Comment by jaime-lynn** [comment]
Initial sweep is completed.
